version: '2.6'

services:
  database:
    container_name: 'ecommerce'
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: 'ecommerce_db'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
      PGDATA: '/var/lib/postgresql/data/pgdata'
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - "${PWD}/local_database:/var/lib/postgres/data"

volumes:
  local_database: